### ISSUE TITLE
ignores noscript tag

### ISSUE THREAD

**Issue by dimzon** [dpacassi/disable-javascript#1]
https://www.w3schools.com/tags/tag_noscript.asp

**Comment by dpacassi** [comment]
Thanks, will be solved in a future release!

**Comment by dpacassi** [comment]
Note to self: Check https://bugzilla.mozilla.org/show_bug.cgi?id=1392090 for workarounds

**Comment by jjkola** [comment]
I would like to note that your solution will not work for noscript elements in head (no content elements allowed) when using html5.
