### ISSUE TITLE
Noscript

### ISSUE THREAD

**Issue by SusanTN** [dpacassi/disable-javascript#16]
You need an options window where various settings could be controlled. One of these should give you the ability to ignore noscript sections that are displayed instead of the content if you have javascript disabled.

**Comment by dpacassi** [comment]
Hi @SusanTN 

Thanks for your report. There is already a settings page, you can access it when right-clicking on the switch icon and select `Open Disable JS settings`.
On Firefox for mobile, you need to open the browser menu, select `Add-ons` -> `Disable JavaScript` -> `Options` to access the settings page.

About your suggestion, is there any case where you **wouldn't** want to see the `<noscript>`-content of web pages if JavaScript is really disabled?
The whole point of the tag is to show the user that JS is not running, which is valid if you've disabled it...

**Comment by dpacassi** [comment]
Closing for now due to inactivity. Feel free to reopen if you can provide more information, Thanks.
