### ISSUE TITLE
Disable Java Script in partnership with Ublock

### ISSUE THREAD

**Issue by Oilinga** [dpacassi/disable-javascript#23]
Hello, 
thank's nice and helpful tool for my Firefox. I'm on testing.
But I have a question regarding "Disable Java Script" in comibination with Ublock. It is usefuel that I create an UBlock rule (see you[ here](https://www.kuketz-blog.de/firefox-noscript-firefox-kompendium-teil5/#more-474132), unfortunately only in German) for "Disable JS" like this example: 
no-csp-reports: noscript-csp.invalid false.

Thank's a lot for your support in advance.
Greetings from South Germany

**Comment by dpacassi** [comment]
Hey Oilinga!

Hmm, as far as I can tell, you probably won't need this web extension if your main goal is to protect your privacy. A mix of uBlock and uMatrix will do more than this web extension currently does.

While this web extension can be used for privacy issues, its main goal is simply to being able to quickly toggle the JavaScript state - which is specially for web developers useful.

Does this answer your question? I'm also happy to discuss this with you in German if language should be a barrier. Just let me know!

Viele Grüsse aus der Schweiz!

**Comment by dpacassi** [comment]
Closing for now due to inactivity. Feel free to reopen if there's still an issue.
