### ISSUE TITLE
What's the shortcut key?

### ISSUE THREAD

**Issue by Dxhs** [dpacassi/disable-javascript#28]
My apologies, but I can't seem to find out what the keybinding for the setting Enable shortcuts option is. 

Linux, Firefox Quantom.

**Comment by dpacassi** [comment]
Hey @Dxhs!

It should be `Alt + Shift + 1` to toggle the JS state and `Alt + Shift + 2` to open the web extension settings.
If you **right click** on the web extension icon in the toolbar and select **About Disable JavaScript**, there's a section with the shortcut bindings.

Hope I was able to help you! Closing this for now but feel free to re-open if you need further support.

Cheers!

**Comment by Dxhs** [comment]
Thanks!

Might help future people if this is updated/added to the plugin's about:addons page or the settings page itself.

**Comment by dpacassi** [comment]
@Dxhs You're right about linking to the about page from the settings page. I've just published a patch release which adds a corresponding link in the settings page.
For the `about:addons` page, the web extension API currently does not allow to add additional buttons.

Still, thanks for your report! Your browser should get the new web extension version within 24 hours.
