### ISSUE TITLE
It makes google docs stop working

### ISSUE THREAD

**Issue by bnegrao** [dpacassi/disable-javascript#3]
After I installed this extension I could not edit my text documents on google docs (docs.google.com). Javascript was enabled so there is no reason for the interference. 

After I disabled the extension I pressed F5 in the document page and It appeared normally.

**Comment by dpacassi** [comment]
Hi @bnegrao!

Thanks for your bug report. There was a bug with v2.0.0 of the web extension, which resulted in a wrong JS enabled/disabled state.

However, I did fix the bug with the v2.0.1 version of the web extension.
Have you tried the latest version of the web extension?

If the bug still persists, please tell me your browser, browser version and OS.
And, if possible, the steps after a clean installation of how I can reproduce the bug.

Thanks for your feedback!

**Comment by dpacassi** [comment]
Closing the issue as it seems to have been fixed with v2.0.1.
Feel free to re-open it with details if it still exists.
