### ISSUE TITLE
Keyboard shortcuts don't work in Vivaldi browser

### ISSUE THREAD

**Issue by stealzy** [dpacassi/disable-javascript#30]
Great extension, thank you!
But only accessible by mouse for me, so I must keep extension panel unhided.
Also it would be cool ability to change shortcuts.

**Comment by dpacassi** [comment]
Hi @stealzy

It seems to be that the Vivaldi browser has currently a bug with shortcuts and web extensions (read e.g. [this](https://forum.vivaldi.net/topic/15274/extension-custom-shortcut-not-working) and [this](https://forum.vivaldi.net/topic/8364/keyboard-shortcuts-for-extensions-is-ineffective)).

However, you can active the shortcuts. Just follow these steps:

1. In the Vivaldi browser, open your [extensions page](vivaldi://extensions)
2. Klick on the botton right on "Keyboard shortcuts"
3. Make sure that you have all dropdowns in the popup set to "Global" and not "Vivaldi"
4. Press OK

Now the shortcuts should work also in Vivaldi.
There you can also change the shortcut keys if you desire.

The shortcuts keys can only be changed in the Vivaldi browser though. At this moment, it is not possible for web extensions to dynamically define shortcut keys. They already have to be defined in the `manifest.json` file, which is a static file (and the web extension API doesn't provide a function to extend/change that information).

Let me know if you have any further questions or bugs!

**Comment by stealzy** [comment]
Thanks for clarification and sorry for my ignorance.

**Comment by dpacassi** [comment]
No problem! Better to report something once too much than too few :)
