### ISSUE TITLE
[Feature Request] "edit" button in domain list

### ISSUE THREAD

**Issue by cgiovanni** [dpacassi/disable-javascript#34]
Hi,

I have just installed this addon and I really like it: it was exactly what I needed!

Just a question: is it possible to add an "edit" button in the "domain list"? By this way I could change entries...

For example this would be useful to change "include sub-domains" option from "no" to "yes" without having to enter an url with the "add" button...

I hope to have explained it well. :-)

Thanks for your work and have a nice day

**Comment by dpacassi** [comment]
Hey @cgiovanni!

That sounds like a reasonable feature! I'll try to implement it in a future release!
Thanks for your idea!

**Comment by cgiovanni** [comment]
Hello @dpacassi,

thanks to you for your fast reply. I am happy you liked my suggestion. :-)
