### ISSUE TITLE
Greasemonkey/Tampermonkey

### ISSUE THREAD

**Issue by TimP69** [dpacassi/disable-javascript#48]
Is it possible for Disable JavaScript to coexist with Greasemonkey and Tampermonkey?  Specifically, is it (or would it one day be) possible to use this extension to disable all JS on a domain EXCEPT for user-scripts that we write ourselves (using either of the monkeys, for example)?

(Currently it seems like disabling JS on a domain prevents Tampermonkey from running on Firefox 65, at least.)

**Comment by dpacassi** [comment]
Hi @TimP69 !

Thanks for your request. I just checked Disable JavaScript with Greasemonkey and they can happily co-exist.
However, there is indeed an issue with Tampermonkey. But I can't find the reason as the code for Tampermonkey is not open source.
Therefor I would suggest you to create an issue on the Tampermonkey project page.
But generally, if they inject the user's JS the same way as Greasemonkey does, there won't be any problems with Disable JavaScript.

Best,
David
