### ISSUE TITLE
About Page: Keyboard Shortcuts on Mac are incorrect

### ISSUE THREAD

**Issue by rrrix** [dpacassi/disable-javascript#53]
MacOS Keyboards (specifically, Apple/Mac keyboards) do not have an "Alt" key. We have an "option" key instead, symbol U+2325 ⌥ OPTION KEY. 
https://en.wikipedia.org/wiki/Option_key

The Shortcuts information on the About page is incorrect, or is simply missing information specifically for Mac users.

Instead of: 
```
Alt + Shift + 1
Toggle JavaScript state
Alt + Shift + 2
Open Disable JavaScript settings
```

You could say:

```
Windows/Linux: Alt + Shift + 1
Mac: ⌥ + Shift + 1
Toggle JavaScript state

Windows/Linux: Alt + Shift + 2
Mac: ⌥ + Shift + 2
Open Disable JavaScript settings
```
Preview of `Disable Javascript` Keyboard Shortcuts in *Chrome Extensions*:
![image](https://user-images.githubusercontent.com/3194704/58975960-2bf95b00-877b-11e9-9c82-3bdf61ca40a6.png)

**Comment by dpacassi** [comment]
Thanks for pointing out @rrrix!
