### ISSUE TITLE
Import and Export the list of URL disabled

### ISSUE THREAD

**Issue by rmagalhaess** [dpacassi/disable-javascript#6]
You could add a button in the "options section" to manually Import, and other button to Export, the list of URL disabled, this will be usefull after a new instalation.

**Comment by dpacassi** [comment]
That's a good idea but in the long term, I was thinking about setting up a server which stores and synchronizes your options (and domains) so you not only have your data after a new installation but also across computers and even different browsers (something like a bookmark manager).

What do you say about dropping this for #8?

**Comment by rmagalhaess** [comment]
Synchronization is better then Import/Export!

**Comment by dpacassi** [comment]
Great, I'll close this issue then so we can focus on #8!
Thanks for your input!
