### ISSUE TITLE
Disable Context-Menu Icon

### ISSUE THREAD

**Issue by bayuah** [dpacassi/disable-javascript#7]
Is there any way to disable context-menu option? I'm prefer it's on top menu-bar icon only.

**Comment by dpacassi** [comment]
This should be programmatically possible.
I will include it in a future release, thanks for your feedback!

**Comment by dpacassi** [comment]
Fixed with https://github.com/dpacassi/disable-javascript/commit/636823bbec3007497a34e92c4b7074d3e5c8825e
